export const DECK_CARDS = [
  // Jade cards
  { id: 'jade-2', suit: 'Jade', value: 2, rank: 2, points: 0, isFaceUp: true },
  { id: 'jade-3', suit: 'Jade', value: 3, rank: 3, points: 0, isFaceUp: true },
  { id: 'jade-4', suit: 'Jade', value: 4, rank: 4, points: 0, isFaceUp: true },
  { id: 'jade-5', suit: 'Jade', value: 5, rank: 5, points: 5, isFaceUp: true },
  { id: 'jade-6', suit: 'Jade', value: 6, rank: 6, points: 0, isFaceUp: true },
  { id: 'jade-7', suit: 'Jade', value: 7, rank: 7, points: 0, isFaceUp: true },
  { id: 'jade-8', suit: 'Jade', value: 8, rank: 8, points: 0, isFaceUp: true },
  { id: 'jade-9', suit: 'Jade', value: 9, rank: 9, points: 0, isFaceUp: true },
  { id: 'jade-10', suit: 'Jade', value: 10, rank: 10, points: 10, isFaceUp: true },
  { id: 'jade-J', suit: 'Jade', value: 'J', rank: 11, points: 0, isFaceUp: true },
  { id: 'jade-Q', suit: 'Jade', value: 'Q', rank: 12, points: 0, isFaceUp: true },
  { id: 'jade-K', suit: 'Jade', value: 'K', rank: 13, points: 10, isFaceUp: true },
  { id: 'jade-A', suit: 'Jade', value: 'A', rank: 14, points: 0, isFaceUp: true },

  // Pagoda cards
  { id: 'pagoda-2', suit: 'Pagoda', value: 2, rank: 2, points: 0, isFaceUp: true },
  { id: 'pagoda-3', suit: 'Pagoda', value: 3, rank: 3, points: 0, isFaceUp: true },
  { id: 'pagoda-4', suit: 'Pagoda', value: 4, rank: 4, points: 0, isFaceUp: true },
  { id: 'pagoda-5', suit: 'Pagoda', value: 5, rank: 5, points: 5, isFaceUp: true },
  { id: 'pagoda-6', suit: 'Pagoda', value: 6, rank: 6, points: 0, isFaceUp: true },
  { id: 'pagoda-7', suit: 'Pagoda', value: 7, rank: 7, points: 0, isFaceUp: true },
  { id: 'pagoda-8', suit: 'Pagoda', value: 8, rank: 8, points: 0, isFaceUp: true },
  { id: 'pagoda-9', suit: 'Pagoda', value: 9, rank: 9, points: 0, isFaceUp: true },
  { id: 'pagoda-10', suit: 'Pagoda', value: 10, rank: 10, points: 10, isFaceUp: true },
  { id: 'pagoda-J', suit: 'Pagoda', value: 'J', rank: 11, points: 0, isFaceUp: true },
  { id: 'pagoda-Q', suit: 'Pagoda', value: 'Q', rank: 12, points: 0, isFaceUp: true },
  { id: 'pagoda-K', suit: 'Pagoda', value: 'K', rank: 13, points: 10, isFaceUp: true },
  { id: 'pagoda-A', suit: 'Pagoda', value: 'A', rank: 14, points: 0, isFaceUp: true },

  // Star cards
  { id: 'star-2', suit: 'Star', value: 2, rank: 2, points: 0, isFaceUp: true },
  { id: 'star-3', suit: 'Star', value: 3, rank: 3, points: 0, isFaceUp: true },
  { id: 'star-4', suit: 'Star', value: 4, rank: 4, points: 0, isFaceUp: true },
  { id: 'star-5', suit: 'Star', value: 5, rank: 5, points: 5, isFaceUp: true },
  { id: 'star-6', suit: 'Star', value: 6, rank: 6, points: 0, isFaceUp: true },
  { id: 'star-7', suit: 'Star', value: 7, rank: 7, points: 0, isFaceUp: true },
  { id: 'star-8', suit: 'Star', value: 8, rank: 8, points: 0, isFaceUp: true },
  { id: 'star-9', suit: 'Star', value: 9, rank: 9, points: 0, isFaceUp: true },
  { id: 'star-10', suit: 'Star', value: 10, rank: 10, points: 10, isFaceUp: true },
  { id: 'star-J', suit: 'Star', value: 'J', rank: 11, points: 0, isFaceUp: true },
  { id: 'star-Q', suit: 'Star', value: 'Q', rank: 12, points: 0, isFaceUp: true },
  { id: 'star-K', suit: 'Star', value: 'K', rank: 13, points: 10, isFaceUp: true },
  { id: 'star-A', suit: 'Star', value: 'A', rank: 14, points: 0, isFaceUp: true },

  // Sword cards
  { id: 'sword-2', suit: 'Sword', value: 2, rank: 2, points: 0, isFaceUp: true },
  { id: 'sword-3', suit: 'Sword', value: 3, rank: 3, points: 0, isFaceUp: true },
  { id: 'sword-4', suit: 'Sword', value: 4, rank: 4, points: 0, isFaceUp: true },
  { id: 'sword-5', suit: 'Sword', value: 5, rank: 5, points: 5, isFaceUp: true },
  { id: 'sword-6', suit: 'Sword', value: 6, rank: 6, points: 0, isFaceUp: true },
  { id: 'sword-7', suit: 'Sword', value: 7, rank: 7, points: 0, isFaceUp: true },
  { id: 'sword-8', suit: 'Sword', value: 8, rank: 8, points: 0, isFaceUp: true },
  { id: 'sword-9', suit: 'Sword', value: 9, rank: 9, points: 0, isFaceUp: true },
  { id: 'sword-10', suit: 'Sword', value: 10, rank: 10, points: 10, isFaceUp: true },
  { id: 'sword-J', suit: 'Sword', value: 'J', rank: 11, points: 0, isFaceUp: true },
  { id: 'sword-Q', suit: 'Sword', value: 'Q', rank: 12, points: 0, isFaceUp: true },
  { id: 'sword-K', suit: 'Sword', value: 'K', rank: 13, points: 10, isFaceUp: true },
  { id: 'sword-A', suit: 'Sword', value: 'A', rank: 14, points: 0, isFaceUp: true },

  // Special cards
  { id: 'special-mahjong', suit: 'Special', value: 'Mahjong', rank: 1, points: 0, isFaceUp: true },
  { id: 'special-dog', suit: 'Special', value: 'Hound', rank: 1, points: 0, isFaceUp: true },
  { id: 'special-phoenix', suit: 'Special', value: 'Phoenix', rank: 15, points: -25, isFaceUp: true },
  { id: 'special-dragon', suit: 'Special', value: 'Dragon', rank: 16, points: 25, isFaceUp: true }
];
