export const PLAY_TYPES = {
  INVALID_PLAY: 'INVALID_PLAY',
  SINGLE: 'SINGLE',
  PAIR: 'PAIR',
  TRIPLE: 'TRIPLE',
  FULL_HOUSE: 'FULL_HOUSE',
  CONSECUTIVE_DOUBLES: 'CONSECUTIVE_DOUBLES',
  STRAIGHT: 'STRAIGHT',
  BOMB_FOUR: 'BOMB_FOUR',
  STRAIGHT_FLUSH_BOMB: 'STRAIGHT_FLUSH_BOMB',
};