export const PLAY_TYPES = {
  INVALID_PLAY: 'INVALID_PLAY',
  SINGLE: 'SINGLE',
  PAIR: 'PAIR',
  TRIPLE: 'TRIPLE',
  FULL_HOUSE: 'FULL_HOUSE',
  STRAIGHT: 'STRAIGHT',
  STRAIGHT_FLUSH: 'STRAIGHT_FLUSH',
  BOMB_FOUR: 'BOMB_FOUR'
};